# Exported from Render on 2026-03-06T11:59:20Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: softmaster.at-nodejs
      runtime: node
      repo: https://github.com/Nodrex-86/softmaster.at-nodejs
      plan: free
      envVars:
      - key: .env
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_USER
        sync: false
      region: frankfurt
      buildCommand: npm install
      startCommand: node server.js
      domains:
      - node.softmaster.at
      autoDeployTrigger: commit
